logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace

spring:
  datasource:
    url: "jdbc:mysql://127.0.01:3306/instagram"
    username: "root"
    password: "password"
    driverClassName: com.mysql.cj.jdbc.Driver
  properties:
    hibernate:
      show_sql: true
      format_sql: true
      use_sql_comments: true