package io.jongyun.graphinstagram.exception

enum class ErrorCode {
    ID_IS_DUPLICATE,
    MEMBER_DOES_NOT_EXISTS,
    CHECK_YOUR_ACCOUNT,
    POST_CONTENT_IS_REQUIRED,
    POST_DOES_NOT_EXISTS,
    CONTENT_MUST_BE_100_LENGTH_OR_LESS,
    THIS_POST_HAS_ALREADY_BEEN_LIKED,
    YOU_DO_NOT_HAVE_PERMISSION,
    POST_LIKES_DOES_NOT_EXISTS,
    ALREADY_FOLLOW,
    DID_NOT_FOLLOW,
}