server:
  port: 9090

dgs:
  graphql:
    graphiql:
      enabled: true
    path: /graphql/**

jwt:
  key: 3f0dc72659384fce9246a9d8af978ee23f0dc72659384fce9246a9d8af978ee23f0dc72659384fce9246a9d8af978ee2

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace

spring:
  datasource:
    url: "jdbc:mysql://127.0.01:3306/instagram"
    username: "root"
    password: "password"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always